#pragma once

#define NODEWATCH_WIFI_SSID         CONFIG_NODEWATCH_WIFI_SSID
#define NODEWATCH_WIFI_PASSWORD     CONFIG_NODEWATCH_WIFI_PASSWORD
#define NODEWATCH_SERVER_URL        CONFIG_NODEWATCH_SERVER_URL
#define NODEWATCH_DEVICE_ID         CONFIG_NODEWATCH_DEVICE_ID
#define NODEWATCH_SEND_INTERVAL_MS  CONFIG_NODEWATCH_SEND_INTERVAL_MS